### ISSUE TITLE
Dataset used to generate the PCA

### ISSUE THREAD

**Issue by DavidGOrtega** [noagarcia/keras_rmac#1]
Hi,

can you please tell me which is the dataset used to generate the PCA?

**Comment by venus024** [comment]
> Hi,
> 
> can you please tell me which is the dataset used to generate the PCA?

i guess PCA matrix needs too be trained by quantities of features obtained by keras_rmac inference.

**Comment by venus024** [comment]
> Hi,
> 
> can you please tell me which is the dataset used to generate the PCA?

found in the author's paper, "PCA-whitening is implemented as a fully connected layer and its weights are computed using American Beauty movie from the training collection."
