### ISSUE TITLE
Dimension mismatched

### ISSUE THREAD

**Issue by EmreOzkose** [noagarcia/keras_rmac#4]
When I load the pre-trained model, I got dimension mismatched error, when I resized images to (224, 224), it was solved. Does it affect the model? I mean r-mac model.

**Comment by nielstenboom** [comment]
I ran into the same issue, am also curious

**Comment by hetianle** [comment]
Using theano backend.

**Comment by noagarcia** [comment]
@EmreOzkose dimension affects the R-MAC model considerably. Are you using theano backend? Dimensions order are different than in the tf backend.
